# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_file', '0002_pdfdatebase_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdatebase',
            name='tag_list',
            field=models.ManyToManyField(blank=True, to='core_file.Tags'),
        ),
    ]
